before_install:
  - sudo apt-get update -qq
  - sudo apt-get install cmake python3
  - if [ $LINUX ]; then sudo apt-get install -qq freeglut3-dev libxmu-dev libxi-dev ; fi
  - echo -e "#ifndef A_R_H_INC\n#define A_R_H_INC\n#define GitVersion ${TRAVIS_JOB_ID}\n#define GitBranch \"${TRAVIS_BRANCH}\"\n#endif // A_R_H_INC" > revision.

env:
  global:
    - PV=r8e PLATF=linux-x86_64 NDK_HOME=${TRAVIS_BUILD_DIR}/android-ndk-${PV} PATH=${PATH}:${NDK_HOME}
  matrix:
    - LINUX=1 TRAVIS_NO_EXPORT=YES
    - LINUX=1 TRAVIS_NO_EXPORT=NO
    - LINUX=1 SHARED_BUILD=ON
    - LINUX=1 SHARED_BUILD=OFF

language: cpp

compiler:
  - clang

script:
  - . ./.travis.sh
