language: cpp

addons:
  apt:
    packages:
      - python3
      - libtinyxml-dev
      - freeglut3-dev
      - libxmu-dev
      - libxi-dev

before_install:
  - echo -e "#ifndef A_R_H_INC\n#define A_R_H_INC\n#define GitVersion ${TRAVIS_JOB_ID}\n#define GitBranch \"${TRAVIS_BRANCH}\"\n#endif // A_R_H_INC" > revision.h
      
install:
  - if [ $TRAVIS_OS_NAME = osx ]; then brew install python3; fi
  
matrix:
  include:
    - os: linux
      env: DEPLOY_FILE=libSOIL.so
      script: . ./.travis.sh
      compiler: clang
    - os: osx
      env: DEPLOY_FILE=libSOIL.dylib
      script: . ./.travis.sh
      compiler: clang
