language: cpp

matrix:
  include:
    - os: linux
      env: DEPLOY_FILE=cimgui.so
      compiler: clang
      script: cmake CMakeLists.txt -G 'Unix Makefiles'; make
    - os: osx
      env: DEPLOY_FILE=cimgui.dylib
      compiler: clang
      script: cmake CMakeLists.txt -G 'Unix Makefiles'; make