language: cpp

before_install:
  - if [ $OSX ]; brew install python3 ; fi
  - if [ $LINUX ]; sudo apt-get update -qq ; fi
  - if [ $LINUX ]; sudo apt-get install cmake python3 ; fi
  - if [ $LINUX ]; then sudo apt-get install -qq freeglut3-dev libxmu-dev libxi-dev ; fi
  - echo -e "#ifndef A_R_H_INC\n#define A_R_H_INC\n#define GitVersion ${TRAVIS_JOB_ID}\n#define GitBranch \"${TRAVIS_BRANCH}\"\n#endif // A_R_H_INC" > revision.h
  
matrix:
  include:
    - os: linux
      env: DEPLOY_FILE=libSOIL.so
      script: . ./.travis.sh
      compiler: clang
    - os: osx
      env: DEPLOY_FILE=libSOIL.dylib
      script: . ./.travis.sh
      compiler: clang
