# AppVeyor file
# http://www.appveyor.com/docs/appveyor-yml

# clone directory
clone_folder: c:\projects\assimp

# branches to build
branches:
  only:
    - master

skip_tags: true    

platform:
    - Win32
    - x64

configuration:
  - 14 2015
  #- 12 2013
  #- MinGW
  #- 10 2010 # only works for x86

init:
- if "%platform%" EQU "x64" ( for %%a in (2008 2010 MinGW) do ( if "%Configuration%"=="%%a" (echo "Skipping unsupported configuration" && exit /b 1 ) ) )

install:
# Make compiler command line tools available
- call c:\projects\assimp\scripts\appveyor\compiler_setup.bat

build_script:
 - cd c:\projects\assimp
 - cmake CMakeLists.txt -G "Visual Studio %Configuration%"
 - msbuild /m /p:Configuration=Release /p:Platform="%PLATFORM%" Assimp.sln

artifacts:
  - path: .\bin\release\assimp-vc140-mt.dll
    name: assimp_lib
    type: File

deploy:
  release: assimp-v$(appveyor_build_version)-$(PLATFORM)
  description: 'Appveyor Build'
  provider: GitHub
  auth_token:
    secure: XSb9h9W4f7bSSB7IQ3m3wngD2WA/hS0mq/aEDynzsVGkETjkjgq8im67ByH7FDX3
  artifact: assimp_lib
  draft: false
  prerelease: false
  on:
    branch: master
