# AppVeyor file
# http://www.appveyor.com/docs/appveyor-yml

# clone directory
clone_folder: c:\projects\assimp

# branches to build
branches:
  only:
    - master

skip_tags: true    

environment:
  matrix:
    - VSType: "Visual Studio 14 2015"
      ArchBits: 32
    - VSType: "Visual Studio 14 2015 Win64"
      ArchBits: 64     

platform:
  - Win32
  - x64

matrix:
  exclude:
    - platform: Win32
      ArchBits: 64
    - platform: x64
      ArchBits: 32
  
install:
# Make compiler command line tools available
- call c:\projects\assimp\scripts\appveyor\compiler_setup.bat

build_script:
 - cd c:\projects\assimp
 - cmake CMakeLists.txt -G "%VSTYPE%"
 - msbuild /m /p:Configuration=Release Assimp.sln

artifacts:
  - path: .\bin\release\assimp-vc140-mt.dll
    name: assimp_lib
    type: File

deploy:
  release: assimp-v$(appveyor_build_version)-$(PLATFORM)
  description: 'Appveyor Build'
  provider: GitHub
  auth_token:
    secure: XSb9h9W4f7bSSB7IQ3m3wngD2WA/hS0mq/aEDynzsVGkETjkjgq8im67ByH7FDX3
  artifact: assimp_lib
  draft: false
  prerelease: false
  on:
    branch: master
